modLoader="javafml"
loaderVersion="[39,)"
license="GPL3"

[[mods]]
modId="cgm"
version="1.3.7"
displayName="CGM+"
logoFile="cgm_banner.png"
authors="An0m3L1"
description="Heavily modified, overhauled and expanded version of zaeonNineZeros CGM Expander Fork."

[[dependencies.cgm]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cgm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cgm]]
    modId="framework"
    mandatory=true
    versionRange="[0.6.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cgm]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cgm]]
    modId="controllable"
    mandatory=false
    versionRange="[0.16.3,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.cgm]]
    modId="backpacked"
    mandatory=false
    versionRange="[2.1.9,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.cgm]]
    modId="shouldersurfing"
    mandatory=false
    versionRange="[1.19.2-4.1.4,)"
    ordering="AFTER"
    side="CLIENT"

[modproperties.cgm]
    catalogueImageIcon="cgm_icon.png"
    catalogueBackground="cgm_background.png"
    configuredBackground="minecraft:textures/block/gray_concrete.png"
